front/.eslintrc.json, front/src/home/home.tsx, front/src/spaceMain/Navigation.tsx, front/src/spaceMain/RTCGameUtils.ts, front/src/spaceMain/spaceMain.tsx, front/src/spaceMain/webGLUtils.ts
=> Feature/me mic on off + 린트 에러 제거

front/package-lock.json, front/src/spaceMain/Navigation.tsx, front/src/spaceMain/spaceMain.css, front/src/spaceMain/spaceMain.tsx
Navigation 컴포넌트 내부에서 peerManger.me의 정보들을 수정합니다.
1. 문제는 변경을 누르지 않고 드롭다운을 닫았다가 다시 키면, 프로필 사진이 현재 아바타 사진 기준으로 뜨지 않는다는 것입니다.
일단 추가하고 나중에 수정하려고 합니다.. 
2. Navigation 컴포넌트 안이 지저분해졌습니다(useState도 많이 쓰고, 전역으로 선언된 배열 같은 것도 있고.. 어떻게 예쁘게 바꿀지 생각해보고 수정하겠습니다).
=> [SW-77][added]navigation 프로필 변경 기능 추가

front/src/index.css, front/src/spaceMain/spaceMain.tsx
=> [SW-91][bugfix]캔버스영역 레이아웃 수정

front/src/index.css, front/src/spaceMain/ImageInfoProvider.ts, front/src/spaceMain/spaceMain.tsx
- useEffect 를 나눠서 관심사 분리. (Image 들이 Load 되기 전과 후로 나뉨 = ImageInfoProvider 가 완성되기 전과 후로 나뉨)
- Image 들이 Load 되기 전에 로딩 상황을 보여줄 새로운 Div 가 return 에 포함됨.
- 같은 Image 를 사용하는 object 들은, 한번 로딩된 공통 Image 를 다시 로드하지 않도록 하여 속도 개선
- 가장 큰 Image 인 background 를 처리하는 로직을 분리하여 속도 개선
- Image 들이 로드될때 마다 spaceMain component 에 로딩상황 업데이트 (setloadStatus)
=> Sw 104/loading page and loading time improving

front/src/index.tsx, front/src/spaceMain/GlobalContext.tsx, front/src/spaceMain/Joystick.tsx, front/src/spaceMain/spaceMain.tsx, front/src/spaceMain/webGLUtils.ts
=> [SW-73][added]pinch 기능 추가/주석 추가

front/public/index.html, front/src/index.css, front/src/index.tsx, front/src/spaceMain/MicOnOff.tsx, front/src/spaceMain/Navigation.tsx, front/src/spaceMain/Options.tsx, front/src/spaceMain/Panel.tsx, front/src/spaceMain/Profile.tsx, front/src/spaceMain/ScreenShare.tsx, front/src/spaceMain/spaceMain.css
spaceMain 레이아웃 수정
모바일 크롬 환경에서 가로로 화면 회전 시
- 양옆 공백
- 하단 홈 인디케이터 영역과 네비게이션 바 겹치는 문제
해결 필요
=> Sw 91/fix navbar layout

.code_deploy/front/appspec.yml, .code_deploy/front/scripts/delete_previous_docker.sh, .code_deploy/front/scripts/run_new_docker.sh, .github/workflows/front_deploy.yml
- 업데이트 시 EC2 인스턴스 내의 프론트 컨테이너
삭제 후 새로운 컨테이너 생성
- 동작할 수 있게 AWS와연동
=> [SW-113][minor_changed]깃헙액션 자동배포 수리

.code_deploy/front/scripts/delete_previous_docker.sh, .code_deploy/front/scripts/run_new_docker.sh, .github/workflows/front_deploy.yml
- 문제 : 배포 후 업데이트가 되지 않는다.
- 인스턴스내에서 docker image를 업데이트 해주지 않아서 발생하던 문제입니다.
=> Sw 113/bugfix/fuck aws

.github/workflows/PR_test.yml
- npm run test 만 테스트에 적용되어 있음
- master로 풀리퀘스트가 만들어질 때 테스트 실행해서
실패 시 bot이 코멘트 달고 풀리퀘 종료
- 성공 시 성공했다고 알려주고 풀리퀘 open 유지
=> [SW-115][added]프론트앤드 CI 구현

front/src/components/SpaceCanvas.tsx, front/src/utils/IceServerList.ts, front/src/utils/RTCGameUtils.ts
=> Sw 132/update stun turn server list

front/src/utils/RTCGameUtils.ts, front/src/utils/webGLUtils.ts
=> [hotfix] 다른사람의 아바타가 볼륨에 따라 변하지 않는 현상해결

front/.env.development, front/src/utils/IceServerList.ts, front/src/utils/RTCGameUtils.ts
간단하게 WebRTC 부분 로그추가와 STUN ,TURN 서버 리스트만 클린업하였습니당!
=> [added]STUN,TURN 서버리스트 클린업, WebRTC 로그 추가

front/src/utils/IceServerList.ts
turn 서버가 정상적으로 연결되지 않는 것 같아서 일단 mdn 보고 iceServer 옵션 추가해봤습니다. 간단해서 그냥 푸쉬할까 하다가 풀리퀘 날립니다 선생님덜
=> [added] iceConfig에 iceTransportPolicy 추가

front/src/components/Navigation.tsx, front/src/components/Panel.tsx, front/src/pages/spacePage/space.css, front/src/utils/RTCGameUtils.ts
- panel 드롭다운 각각의 항목에서 뒤로가기 추가.
- 사용자 클릭 시 사용자 목록 볼 수 있음.
- 메시지는 구현 예정으로 남겨둠.
=> [SW-54][added]panel 드롭다운에 사용자 기능 추가

front/src/components/Navigation.tsx, front/src/components/Panel.tsx, front/src/components/UserDropDown.tsx, front/src/utils/RTCGameUtils.ts
제가 만들었던 버전에 혼리님이 수정해주신 코드 머지합니다 ㅎㅎ.
=> [SW-54][merged]업데이트 된 브랜치 merge

back/src/signaling.gateway.ts, front/.env.development, front/.env.production, front/src/components/Navigation.tsx, front/src/components/SpaceCanvas.tsx, front/src/pages/spacePage/Space.tsx, front/src/setupTests.ts, front/src/utils/RTCGameUtils.ts, front/src/utils/RTCSignalingHelper.ts, front/src/utils/__test__/AudioAnalyser.test.ts, front/src/utils/__test__/RTCSignalingHelper.test.ts, front/src/utils/webGLUtils.ts, front/tsconfig.json
- RTCGameUtils.ts 에서 socket 부분만 떼어내서 RTCSignalingHelper.ts 로 옮겼습니다.
- Me 에서 오디오 분석하는 부분만 떼어내서 AudioAnalyser 클레스로 옮겼습니다.
- AudioAnalyser 클레스 테스터를 작성하였습니다.
- 이외에 약간의 리펙토링 부분들이 있습니다. (private 나 get set, readonly ... )
=> Sw 111/peer manager refactoring

.github/workflows/docs_deploy.yml, front/src/pages/homePage/__test__/Home.test.tsx
- 배포 디렉토리가 잘못되어있어서 업데이트가 제대로 안되던 문제 수정
- coverage 배포 항상 master 최신으로만 남도록 수정
=> [SW-148][bugfix]docs_deploy 배포 오류 수정

front/public/naver46b0a36e43fa8c02cf76be203d6c122b.html
- front/public 에 naver로 시작하는 html 파일 추가
=> [SW-138][added]네이버 웹마스터 소유확인용 html파일 추가

front/package-lock.json, front/package.json, front/src/components/Navigation.tsx, front/src/components/Options.tsx, front/src/components/ScreenShare.tsx, front/src/components/SelectDevice.tsx, front/src/components/Setting.tsx, front/src/components/__test__/Panel.test.tsx, front/src/pages/spacePage/space.css, front/src/utils/RTCGameUtils.ts
화면 공유 레이아웃 완성,
화면 공유 기능 추가
이후 드로우 기능 추가하면서 화면공유 부분 지속적으로 유지보수해갈 예정
=> Sw 142/sw 63/screen share and device select

front/src/components/EnterRoom.tsx
=> [SW-167][fixed]홈에서 엔터 눌렀을 때 입장하도록 변경

front/src/components/Profile.tsx
- 변경사항 없을 시 엔터는 안 됨.. 더 찾아보겠습니다
=> [SW-154][fixed]프로필 변경 후 엔터 눌러도 변경사항 저장

front/package-lock.json, front/package.json, front/src/components/ScreenShare.tsx, front/src/components/screenShare.css
- (X) 버튼을 삭제하고 clear 버튼을 추가했습니다.
- 그림을 그릴 때 사용하는 line 의 색상과 굵기를 조절 할 수 있도록 컨트롤러를 추가하였습니다.
=> Sw 162/color picker and line width picker

front/src/components/Navigation.tsx, front/src/components/Panel.tsx, front/src/components/ScreenShare.tsx, front/src/components/SpaceCanvas.tsx, front/src/components/__test__/Panel.test.tsx, front/src/utils/RTCGameUtils.ts
- peerConnection 의 dataChannel 을 이용한 onMessage 추상화 
- share screen 드로우 기능 추가
- panel.test.tsx 약간의 코드 변경 (props interface 변경 때문에)
=> Sw 155/draw shared screen

front/package-lock.json, front/src/components/Messenger.tsx, front/src/components/Navigation.tsx, front/src/components/SpaceCanvas.tsx, front/src/pages/spacePage/Space.tsx, front/src/pages/spacePage/space.css, front/src/utils/RTCGameUtils.ts, front/src/utils/webGLUtils.ts
webGLUtils.ts의 drawAvatar 부분이 조금 더러워져서 정리 필요
=> [SW-145][added]말풍선 추가

front/src/components/Messenger.tsx, front/src/components/Panel.tsx, front/src/pages/spacePage/space.css
Panel.tsx, Messenger.tsx 약간 수정했습니다. 바로 머지 하겠습니다..
=> Sw 172/fix messenger propdown

front/src/components/Navigation.tsx, front/src/components/ScreenShare.tsx, front/src/components/SpaceCanvas.tsx, front/src/utils/RTCGameUtils.ts
- 동시에 여러명이 하나의 화면에 그림을 그릴 때 펜이 꼬이는 현상 해결
- 화면 공유한 채로 browser 를 종료하였을 때 화면 공유가 계속 남는 현상 해결
- 늦게 공유된 화면이 zIndex 가 더 낮아서 아래로 내려가 안보이던 현상 해결
=> Sw 171/sreen draw line start pos bugfix

front/src/components/Navigation.tsx, front/src/components/ScreenShare.tsx
nickname 으로 표기되도록 수정
- 간단하게 기능 구현이 되었습니다.
=> [SW-149][SW-174][added] dropdown 바로 내려가게 수정, sharedScreen 대신

front/src/components/ScreenShare.tsx, front/src/components/screenShare.css
- 간단하게 그리기 컨트롤러 (선 컬러, 선 두께) 를 sharedScreen 안으로 옮겼습니다.
=> Sw 162/change pencil controller location

front/src/components/Navigation.tsx, front/src/pages/spacePage/space.css
=> Sw 196/navbar design

front/src/components/screenShare.css
간단하게 css 만 아주 짧게 수정하여 바로 머지하겠습니다 선생님들 ^_^;;
=> [SW-199] setting page 의 slider 가 sharedScreen.css 에 영향을 받는 문제

front/src/components/Messenger.tsx, front/src/components/Navigation.tsx, front/src/components/Panel.tsx, front/src/components/Profile.tsx, front/src/components/__test__/Profile.test.tsx, front/src/pages/spacePage/space.css
=> Sw 203/update messenger dropdown

front/public/index.html
index.html의 meta태그에서 description의 conten를 수정
=> [SW-208][added]네이버 검색시 서비스 설명란 수정

front/src/utils/pixiUtils/PeerAvatar.ts, front/src/utils/pixiUtils/World.ts
피어의 collisionBox를 null로 셋팅했습니다.
=> [SW-228][minor_changed]피어 충돌 안 되게 수정

front/src/pages/spacePage/space.css, front/src/utils/pixiUtils/metaData/ImageMetaData.ts
- sharedScreen 아이콘 안보이는 현상 해결
- 초기 setting 의 일부 avatar 선택 못하던 현상 해결
=> Sw 240/sw 249/bugfix

front/src/components/SpaceCanvas.tsx, front/src/utils/pixiUtils/PixiCanvas.ts, front/src/utils/pixiUtils/SceneManager.ts
=> [SW-233] 안티패턴 제거

front/src/components/Options.tsx, front/src/components/Panel.tsx
옵션 분리하면서 살펴보니 코드가 매우 더럽네요. 나중에 틈내서 정리하겠습니다.
=> [SW-254][minor_changed]옵션 분리해서 패널에 넣었습니다.

front/src/components/Messenger.tsx, front/src/pages/spacePage/space.css
- 메신저 input가 화면 크기에 맞게 늘어나지 않는 현상 픽스
- 메신저의 input에 focus가 안가는 현상 픽스
=> 메신저 css, input focus 핫픽스

front/src/components/Messenger.tsx
=> [SW-272][hotfix]메신저 글자수 제한

front/src/pages/spacePage/space.css
볼륨바 너무 안 작아지게 css만 간단하게 수정했습니다
=> [SW-252][fix]볼륨바 min-width 수정

front/src/utils/pixiUtils/PlayerKeyboard.ts
=> [SW-271][hotfix]키보드 리셋(visibility -> reset)
